# Matrix Basics

Link to the Youtube tutorial video: https://www.youtube.com/watch?v=Wibxjrxf5ko&list=PLeo1K3hjS3uu7CxAacxVndI4bE_o3BDtO&index=10


1) Numpy module allows the manipulation of matrices in python
2) You can think a numpy array as a matrix
3) Use dot() of numpy module to perform dot product between matrices

**Matrices involved in this tutorial:**  </br>
<img src="hidden\photo1.png" alt="This image is a representation of the simple neural network" style="width: 600px;"/>  <br />  <br />

In [17]:
import numpy as np

# Create the numpy array (matrix) called revenue
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
print('Numpy array (matrix) called revenue:\n', revenue)

# Create the numpy array (matrix) called expenses
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])
print('\nNumpy array (matrix) called expenses:\n', expenses)

# Calculate profit by performing matrix subtraction
profit = revenue - expenses
print('\nNumpy array (matrix) called profit:\n', profit)

Numpy array (matrix) called revenue:
 [[180 200 220]
 [ 24  36  40]
 [ 12  18  20]]

Numpy array (matrix) called expenses:
 [[ 80  90 100]
 [ 10  16  20]
 [  8  10  10]]

Numpy array (matrix) called profit:
 [[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


**Matrices involved in this tutorial:**  </br>
<img src="hidden\photo2.png" alt="This image is a representation of the simple neural network" style="width: 600px;"/>  <br />  <br />

In [18]:
# Create the numpy array (matrix) called price_per_unit
price_per_unit = np.array([[1000,400,1200]])
print('Numpy array (matrix) called price_per_unit:\n', price_per_unit)

# Create the numpy array (matrix) called units
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
print('\nNumpy array (matrix) called units:\n', units)

# Calculate the Total Sale (revenue) by performing dot product using dot() of numpy module [Note: Here, 1x3 matrix * 3x3 matrix]
total_sale = np.dot(price_per_unit, units)
print('\nNumpy array (matrix) called total_sale:\n', total_sale)

Numpy array (matrix) called price_per_unit:
 [[1000  400 1200]]

Numpy array (matrix) called units:
 [[30 40 50]
 [ 5 10 15]
 [ 2  5  7]]

Numpy array (matrix) called total_sale:
 [[34400 50000 64400]]
